### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by tarantrulla** [bundesAPI/jobsuche-api#10]
Token abholen geht noch.
Aber seit heute kann man ihn nicht mehr benutzen.
Es geht weder am Terminal noch von der BundesApi-Seite.
Zurück kommt immer:
503 Service Unavailable
No server is available to handle this request.

**Comment by LilithWittmann** [comment]
Bitte die aktualisierte Dokumentation benutzen.

**Comment by tarantrulla** [comment]
Danke, es geht wieder.
Ihr seid die größten. <3<3<3
