### ISSUE TITLE
Jobdetails Header

### ISSUE THREAD

**Issue by baldzuhnc** [bundesAPI/jobsuche-api#13]
Ist der Header für die Jobsdetails der gleiche wie für die Jobsuche? Also "OAuthAccessToken = []". Jobsuche funktioniert damit, jobdetails jedoch leider nicht. Zurück kommt ein 404 – auch mit dem Querry aus der Dokumentation.

**Comment by LilithWittmann** [comment]
Habe ein Beispiel hinzugefügt: https://github.com/bundesAPI/jobsuche-api/blob/main/api_example.py#L46
Nur ein bisschen base64…
```python

    headers = {
        'User-Agent': 'Jobsuche/2.9.3 (de.arbeitsagentur.jobboerse; build:1078; iOS 15.1.0) Alamofire/5.4.4',
        'Host': 'rest.arbeitsagentur.de',
        'OAuthAccessToken': jwt,
        'Connection': 'keep-alive',
    }

    response = requests.get(
        f'https://rest.arbeitsagentur.de/jobboerse/jobsuche-service/pc/v2/jobdetails/{(base64.b64encode(job_ref.encode())).decode("UTF-8")}',
        headers=headers, verify=False)

    return response.json()
```

**Comment by rlaemmel** [comment]
Hallo.

Für "jobdetails" hat der Hinweis von @LilithWittmann geholfen.
Das hier funktioniert also:

`requests.get(f'https://rest.arbeitsagentur.de/jobboerse/jobsuche-service/pc/v2/jobdetails/{(base64.b64encode(hashId.encode())).decode("UTF-8")}',
        headers=headers, verify=False)`

**Allerdings für "bewerbung" funktioniert der analoge Ansatz nicht:**

`requests.get(f'https://rest.arbeitsagentur.de/jobboerse/jobsuche-service/pc/v2/jobs/{(base64.b64encode(hashId.encode())).decode("UTF-8")}/bewerbung',
        headers=headers, verify=False)`

gibt dies zurück:

`{'timestamp': '2022-02-26T11:32:20.887871796Z', 'logref': 'f7aa9', 'messages': [{'code': 'AAS_WRONG_PARAMETERS'}]}`

In der neuen Dokumentation is von captcha headers die Rede. Allerdings konnte ich kein funktionierende Beispiel finden. Siehe auch hier:

https://github.com/bundesAPI/jobsuche-api/search?q=captcha
