### ISSUE TITLE
AAS_WRONG_PARAMETERS

### ISSUE THREAD

**Issue by hbakouane** [bundesAPI/jobsuche-api#18]
Hallo, wenn ich die JobDetails API benutze, erhalte ich diese problem obwohl alles gut ist!!
![image](https://user-images.githubusercontent.com/57842491/154974323-b2960203-0440-4ff8-be01-9f400305ed1d.png)

![image](https://user-images.githubusercontent.com/57842491/154974090-cb3bd850-00fc-4d6c-acd2-d6d958ebc0f9.png)
Hier sind mein Headers
![image](https://user-images.githubusercontent.com/57842491/154974050-21eceabf-ac0e-41b1-aea0-0e5d7bffce66.png)

Danke Sehr!!

**Comment by hbakouane** [comment]
Kann jemand mir helfen bitte!!

**Comment by rlaemmel** [comment]
Siehe [LilithWittmann](https://github.com/LilithWittmann) commented [on Nov 30, 2021](https://github.com/bundesAPI/jobsuche-api/issues/18#issuecomment-982996625)

Der HashId muss sorgsam repräsentiert werden. 
Etwa so:

`requests.get(f'https://rest.arbeitsagentur.de/jobboerse/jobsuche-service/pc/v2/jobdetails/{(base64.b64encode(hashId.encode())).decode("UTF-8")}',
        headers=headers, verify=False)`
