### ISSUE TITLE
API-Beispiel jobs/{hashId}/bewerbung?

### ISSUE THREAD

**Issue by rlaemmel** [bundesAPI/jobsuche-api#19]
Ich versuche gerade von der alten api-con auf die aktuelle zu migrieren.

Bei der Abfrage von "jobs/{hashId}/bewerbung" bekomme ich:

`{'timestamp': '2022-02-26T11:56:42.757607145Z', 'logref': '2f6fe', 'messages': [{'code': 'AAS_WRONG_PARAMETERS'}]}`

Das ist der Request:

`requests.get(f'https://rest.arbeitsagentur.de/jobboerse/jobsuche-service/pc/v2/jobs/{(base64.b64encode(hashId.encode())).decode("UTF-8")}/bewerbung', headers=headers, verify=False)`

Das Gegenstück für "jobdetails/{hashId}" funktioniert:

`requests.get(f'https://rest.arbeitsagentur.de/jobboerse/jobsuche-service/pc/v2/jobdetails/{(base64.b64encode(hashId.encode())).decode("UTF-8")}', headers=headers, verify=False)`

Vielen Dank für Hilfe.

**Comment by rlaemmel** [comment]
Auch spricht die Dokumentation an einer Stelle https://github.com/bundesAPI/jobsuche-api/blob/main/README.md von pc/v4/jobs/{hashId}/bewerbung -- dort kommt ein 404. 

An anderen Stellen https://jobsuche.api.bund.dev und https://github.com/bundesAPI/jobsuche-api/blob/main/python-client/README.md spricht die Dokumentation von pc/v2/app/jobs/{hashId}/bewerbung -- dort kommt das:

```
{'timestamp': '2022-02-26T16:57:12.981874665Z', 'logref': '159ae', 'messages': [{'code': 'AAS_WRONG_PARAMETERS'}]}
```

Bei jobdetails habe ich keine Probleme mit pc/v2/jobdetails/{hashId}.

**Comment by hbakouane** [comment]
Ich habe den gleichen Problem, @LilithWittmann

**Comment by hbakouane** [comment]
@LilithWittmann Könnten Sie bitte uns helfen?

**Comment by superman88** [comment]
push @LilithWittmann

**Comment by superman88** [comment]
push @AndreasFischer1985 @LilithWittmann
