### ISSUE TITLE
kontakt Details API

### ISSUE THREAD

**Issue by BassemDev** [bundesAPI/jobsuche-api#30]
Gibt noch ein kontakt API für stellen/jobs , z.b email oder Handynummer als Response für jeden stelle ?
Ich habe versucht diese APi aber ich glaube das ist funktioniert nicht:
https://rest.arbeitsagentur.de/jobboerse/jobsuche-service/pc/v2/jobs/MTAwMDAtMTE4OTg1MDQzNS1T/bewerbung 

Und für die Datails APi z.b : https://rest.arbeitsagentur.de/jobboerse/jobsuche-service/pc/v2/jobdetails/MTAwMDAtMTE4OTg0NTgwNy1T
ich glaube das gibt normalerweise links properties aber ich glaube das ist vermisst , also **links** properties von details Response ist nicht da !

**Comment by BassemDev** [comment]
Is there any update from your side ?

**Comment by AndreasFischer1985** [comment]
I am going to update the JobDetails schema in the near future. 
JobApplicationDetails were removed from the openapi.yaml due to insufficient documentation.

**Comment by BassemDev** [comment]
I am happy to get feedback and answer from you , it would be amazing if you update it soon because I would like to make great product from this amazing API.

Please let me know if you need any help otherwise , hope that this does not take that long and thank you for your effort @AndreasFischer1985
