### ISSUE TITLE
Missing values in openapi.yaml "components -> securitySchemes -> clientCredAuth" result in error when using openapi-python-client

### ISSUE THREAD

**Issue by mirkoruether** [bundesAPI/jobsuche-api#5]
Wenn man das Tool openapi-python-client nutzen möchte, um sich schnell einen python client für die API generieren zu lassen, schmeißt dieses leider einen Fehler.

```
Error(s) encountered while generating, client was not created

Failed to parse OpenAPI document

2 validation errors for OpenAPI
components -> securitySchemes -> clientCredAuth -> flows -> clientCredentials -> scopes
  field required (type=value_error.missing)
components -> securitySchemes -> clientCredAuth -> $ref
  field required (type=value_error.missing)
```

Reproduzieren geht so:
```
pip install openapi-python-client
openapi-python-client generate --url https://jobsuche.api.bund.dev/openapi.yaml
```

Leider selbst wenig Ahnung von OpenAPI ...

**Comment by thacoon** [comment]
Ich habe auch kaum Erfahrung mit OpenAPI, aber ich denke du musst noch die scopes setzen.

Die scopes sollten folgende sein: _apok_metasuggest, jobboerse_suggest-service, aas, jobboerse_kataloge-service, jobboerse_jobsuche-service, headerfooter_hf, apok_hf, jobboerse_profil-service_
Zumindestens sind das die scopes die im JWT bei mir im Browser angegeben sind.

Wenn die scopes definiert sind, wird der Python Client bei mir generiert (mit Warnungen). $ref war nicht nötig bei mir.

[Describing OAuth 2.0 Using OpenAPI](https://swagger.io/docs/specification/authentication/oauth2/#scopes-extra)

**Comment by mirkoruether** [comment]
Danke für die Infos! Ich habe mal eine Lösung als pull request vorgeschlagen, in der einfach eine leere scope definition hinzugefügt wird. Vermute mehr ist ja in dieser reverse-engineering Situation nicht nötig/sinnvoll... Hab von OpenAPI und auch OAuth aber wie gesagt wirklich keine Ahnung.

Der Generator rennt so auf jeden Fall :)
